### ISSUE TITLE
FPS

### ISSUE THREAD

**Issue by SaiSandeepKantareddy** [Rahul24-06/COVID-19-Authorized-Entry-using-Face-Mask-Detection#1]
Hi, what is the FPS you achieved on real time and you are directly using detection or face detection with classification?
Thanks for the info.

**Comment by Rahul24-06** [comment]
With the Image classification, I was able to achieve ~ 20 to 30 FPS.

**Comment by SaiSandeepKantareddy** [comment]
> With the Image classification, I was able to achieve ~ 20 to 30 FPS.

How were you able to do just classification without detection in the frame as it shows a bounding box around the face?

**Comment by Rahul24-06** [comment]
I've tried both face detection and classification, but it turns out that, classification gave more accurate results for this project.

**Comment by SaiSandeepKantareddy** [comment]
> I've tried both face detection and classification, but it turns out that, classification gave more accurate results for this project.

One thing out of curiosity I am asking you is that did you just do classification and draw the bounding boxes that are what you are trying to say, if so if you can please enclose the model to this mail id that would be of great help, sandeepsaireddy123@gmail.com
